Terdapat beberapa packages pada python yang sangat berguna ketika melakukan proyek data analysis, seperti python, numpy, math, dan lain-lain, tergantung dengan kebutuhan kita

## 1. Math 

Math merupakan salah satu packages yang ada pada python yang memungkinkan untuk melakukan operasi matematis pada python

In [1]:
# import packages math
import math



In [2]:
# Example 1 : phi 
print(" pi =", math.pi)

 pi = 3.141592653589793


In [ ]:
# Example 2: Square Root
x = 25
sqrt_x = math.sqrt(x)
print("Square root of", x, "is:", sqrt_x)

In [3]:
x = 100
sqrt_x = math.sqrt(x)

In [4]:
sqrt_x

10.0

In [8]:

# Example 3: Fungsi Trigonometri
angle = 45  # in degrees
sin_angle = math.sin(math.radians(angle))
cos_angle = math.cos(math.radians(angle))
print("Sin of", angle, "degrees is:", sin_angle)  
print("Cos of", angle, "degrees is:", cos_angle)  




Sin of 45 degrees is: 0.7071067811865475
Cos of 45 degrees is: 0.7071067811865476


In [5]:
angle = 90
sin_angle = math.sin(math.radians(angle))
cos_angle = math.cos(math.radians(angle))

In [6]:
sin_angle

1.0

In [7]:
cos_angle

6.123233995736766e-17

In [ ]:
# Example 4: Logarithm
num = 100
log_num = math.log10(num)
print("Logarithm base 10 dari", num, "adalah :", log_num)



In [9]:
num=100
log_num = math.log10(num)

In [10]:
log_num

2.0

In [ ]:
# Example 5: Exponentiation
base = 2
exponent = 5
result = math.pow(base, exponent)
print(base, "pangkat", exponent, "adalah :", result) 



In [11]:
base = 2
exponent = 5
result = math.pow(base, exponent)

In [12]:
result

32.0

In [13]:
# Example 6: Pembulatan
value = 3.7
rounded_value = math.ceil(value)
print("Pembulatan ke atas dari ", value, "adalah :", rounded_value)  
rounded_value = math.floor(value)
print("Pembulatan ke bawah dari ", value, "adalah :", rounded_value)  

Pembulatan ke atas dari  3.7 adalah : 4
Pembulatan ke bawah dari  3.7 adalah : 3


Contoh diatas merupakan beberapa penggunaan dari packages math yang ada pada python , sejatinya terdapat banyak sekali fungsi fungsi yang dapat dilakukan oleh package math apabila kalian ingin mempelajari lebih lanjut dapat membuka link dokumentasi berikut :
 https://docs.python.org/3/library/math.html

## 2. Numpy

Numpy juga merupakan packages yang digunakan untuk operasi numerikal, berbeda dengan math yang menyediakan dasar dasar operasi matematika, sedangkan numpy lebih ke arah penggunaan numerikal, salah satu contohnya adalah penggunaan array. Array merupakan salah satu struktur data yang sangat sering kita jumpai ketika melakukan operasi numerikal pada python dan menggunakan algoritma algoritma tertentu seperti linear algebra, generate random number, dll. Pada kesempatan ini kita akan fokus kedalam penggunaan numpy dalam array manipulation

In [15]:
# import packages numpy
import numpy as np 

In [14]:
#array dengan dimensi 4 x 1
array1 = np.array([1, 3, 5, 7])
print('array1 = ', array1)

NameError: name 'np' is not defined

In [18]:
array = np.array([1, 3, 4, 6])

In [19]:
array

array([1, 3, 4, 6])

In [ ]:
# array dengan dimensi  2 x 3
array2=np.array([[1, 2, 3], [4, 5, 6]])
print(f"array2 =\n {array2}\n")

In [21]:
array2 = np.array([[1,3,4], [5,5,6]])

In [22]:
array2

array([[1, 3, 4],
       [5, 5, 6]])

In [24]:
#melihat ukuran pada array
print(array.shape)
print(array2.shape)

(4,)
(2, 3)


In [25]:
# mengubah ukuran array dari 6x1 menjadi 2x3
array4 = np.array(range(6))
array4

array([0, 1, 2, 3, 4, 5])

In [ ]:
# mengubah ukuran array dari 6x1 menjadi 2x3
array4 = np.array(range(6)).reshape((2, 3))
print(f"array 4 =\n {array4}\n")


In [26]:
array4 = np.array(range(6)).reshape(2,3)

In [27]:
array4

array([[0, 1, 2],
       [3, 4, 5]])

In [28]:
#array transpose
array4.transpose()

array([[0, 3],
       [1, 4],
       [2, 5]])

In [29]:
#menggabungkan beberapa array
a = np.array([1,2,5])
b = np.array([3,4,5])
c = np.array([7,8,9])
np.concatenate((a, b, c))

array([1, 2, 5, 3, 4, 5, 7, 8, 9])

### Axis in concatenate array
Pada numpy array terdapat parameter axis, yang menentukan dimensi dari penggabungan dua buah array atau lebih , axis akan menentukan apakah array akan digabungkan ke arah vertikal atau horizontal

In [30]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7,8]])



In [31]:
print(a)
print(b)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]


In [32]:
#axis 1 menggabungkan array secara horizontal 
np.concatenate((a,b), axis=1)

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [33]:
#axis 0 menggabungkan array secara vertikal
np.concatenate((a,b), axis=0)

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

# 2. Pandas

Pandas merupakan salah satu package data analysis yang menyediakan data struktur yang termasuk mudah digunakan yaitu series dan data frame. Pandas dibuat untuk membantu kita dalam melakukan manipulasi pada struktur data sehingga akan membantu ketika sedang melakukan proyek data analysis

In [34]:
# import pandas 
import pandas as pd


In [ ]:
pip install pandas 

In [35]:
#import pandas
import pandas as pd

### **Series**
Series adalah array satu dimensi yang dapat menyimpan berbagai tipe data, termasuk tipe data campuran. Label baris dalam Seri disebut indeks. Kita dapat melakukan manipulasi kepada struktur data seperti list, tuple dan dictionaries dengan mengubah menjadi Series

In [ ]:
# creating a series from list 
list = ['a', '2012-02-01', 100, 10.2]
s = pd.Series(list)
s

In [36]:
list = [1, 3, 4, 5]
s = pd.Series(list)

In [37]:
s

0    1
1    3
2    4
3    5
dtype: int64

Series merupakan one dimentional array

In [38]:
# cek tipe data
print(type(list))
print(type(s))

<class 'list'>
<class 'pandas.core.series.Series'>


In [39]:
# converting dict to Series
d = {'name' : 'rian', 'tanggal lahir' : '2010-09-08', 'nilai' : 100, 'predikat' : 'A'}
ds = pd.Series(d)
ds

name                   rian
tanggal lahir    2010-09-08
nilai                   100
predikat                  A
dtype: object

Pada dictionary terlihat bahwa series akan mengubah labelnya menjadi key yang ada pada dictionary tersebut

### **DataFrame**
Berbeda dengan series data frame merupakan two dimensional label data structure, yang sangat mirip dengan struktur pada excel/spreadsheet dan tabel dan kolom yang ada pada sql, dia tertiri dari baris dan kolom yang dapat menampung berbagai tipe data. Dataframe akan sangat berguna ketika bekerja dengan data yang terstruktur dan berlabel.

In [ ]:
# Create a DataFrame from a dictionary of lists
data = {'Name': ['Alice', 'Bob', 'Charlie'],
        'Age': [25, 30, 35],
        'City': ['New York', 'London', 'Paris']}
df = pd.DataFrame(data)
df



In [40]:
data = {'Name': ['Alice', 'Bob', 'Charlie'],
        'Age': [25, 30, 35],
        'City': ['New York', 'London', 'Paris']}

In [41]:
df = pd.DataFrame(data)

In [42]:
df

Name  Age      City
0    Alice   25  New York
1      Bob   30    London
2  Charlie   35     Paris

Data yang terbentuk dari dictionary akan membentuk sebuah dataframe yang terlihat seperti tabel dan kelihatan rapi antara kolom dan barisnya.

In [43]:
# cek tipe data
type(df)

pandas.core.frame.DataFrame

In [44]:
# Akses kolom menggunakan index kolom
df['Name']

0      Alice
1        Bob
2    Charlie
Name: Name, dtype: object

In [47]:
df['Age']

0    25
1    30
2    35
Name: Age, dtype: int64

In [48]:
# membuat kolom baru
df['Jenis Kelamin'] = ['perempuan','laki-laki', 'laki-laki']
df

Name  Age      City Jenis Kelamin
0    Alice   25  New York     perempuan
1      Bob   30    London     laki-laki
2  Charlie   35     Paris     laki-laki

In [49]:
# menghapus kolom del
del df['Jenis Kelamin']
df

Name  Age      City
0    Alice   25  New York
1      Bob   30    London
2  Charlie   35     Paris

kolom baru berhasil terhapus